name: vault_app
description: a simple vault app
version: 1.0.0+3
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  audioplayers: ^1.0.1
  better_player: ^0.0.83
  bloc: ^8.0.3
  cloud_firestore: ^3.4.1
  cloud_functions: ^3.3.3
  contacts_service: ^0.6.3
  crypto: ^3.0.2
  csv: ^5.0.1
  easy_localization: ^3.0.1
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  file_picker: ^4.6.1
  firebase_auth: ^3.5.1
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_credit_card: ^3.0.1
  flutter_downloader: ^1.8.1
  flutter_inappwebview: ^5.4.3+7
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.2
  flutter_secure_storage: ^5.0.2
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.1+1
  flutter_view: ^1.0.1
  font_awesome_flutter: ^10.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  just_audio: ^0.9.28
  local_auth: ^2.1.0
  mime_type: ^1.0.0
  open_file: ^3.2.1
  package_info: ^2.0.2
  path: ^1.8.1
  path_provider: ^2.0.11
  pdf: ^3.8.1
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  random_string: ^2.3.1
  rxdart: ^0.27.5
  timeago: ^3.2.2
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  webview_flutter: ^3.0.4
  wechat_assets_picker: ^7.3.2

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  generate: true
